### ISSUE TITLE
SystemElements.show_displacement() renders the displacement incorrectly for the same structure.

### ISSUE THREAD

**Issue by thisisapple** [ritchie46/anaStruct#326]
I define a 2D frame as shown in this figure. I checked the internal forces and the displacement. The issue is that the displacement was rendered incorrectly for the original 2D frame.

### Nodal Displacement
I checked the nodal displacement for Node No. 4 of the original frame, which will be Node No. 5 for the second frame. I noticed that the movement is the same at the same location. **Surprisingly, you see very different outcomes from the 
SystemElements.show_displacement() for the same structure as shown below.**

### Conclusion
I think `SystemElements.show_displacement()` is causing the problem. The show_displacement function is rendering the displacement incorrectly.

```
d = structure.get_node_displacements(node_id=4)
print(d)
```
Below is the nodal result.
`{'id': 4, 'ux': np.float64(-0.016609195402298816), 'uy': np.float64(-0.25626438577585275), 'phi_z': np.float64(0.0027801727729883222)}`

## Original 2D Frame (a total of **3 beam elements**)
I apply  a line load to the last beam element
![image](https://github.com/user-attachments/assets/6c182f94-6967-4cc9-9655-246030b62f98)
The problem is that the show_displacement() cannot render the results correctly. 
![image](https://github.com/user-attachments/assets/626f56d1-7168-4f5c-8edf-3d51c4705a45)

```
from anastruct import SystemElements

## Input
E_s = 29E3
I = 500
A = 102.5
EI = E_s * I
EA = E_s * A

structure = SystemElements(EI=EI, mesh=100)
structure.add_element(location=[
    [0, 59.5],
    [0, 17]
])

structure.add_element(location=[
    [0, 17],
    [0, 0]
])


structure.add_element(location=[
    [0, 0],
    [100, 0]
])


structure.add_support_hinged(node_id=1)
structure.add_support_hinged(node_id=2)

# I assign the same line load to the structure.
structure.q_load(q=-0.125, element_id=[3]) 

structure.show_structure()
structure.solve()
structure.show_displacement()
```

## Same 2D Structure with **4 beam elements**
I redefine the structure by splitting the last element into two elements, the displacement is correct. 

```
from anastruct import SystemElements

## Input
E_s = 29E3
I = 500
A = 102.5
EI = E_s * I
EA = E_s * A

structure = SystemElements(EI=EI, mesh=100)
structure.add_element(location=[
    [0, 59.5],
    [0, 17]
])

structure.add_element(location=[
    [0, 17],
    [0, 0]
])

structure.add_element(location=[
    [0, 0],
    [50, 0]
])

structure.add_element(location=[
    [50, 0],
    [100, 0]
])

structure.add_support_hinged(node_id=1)
structure.add_support_hinged(node_id=2)

# I assign the same line load to the structure.
structure.q_load(q=-0.125, element_id=[3,4]) 

structure.show_structure()
structure.solve()
structure.show_reaction_force()
structure.show_displacement()
```

![image](https://github.com/user-attachments/assets/13832843-8a06-4525-a198-f9b810551557)
![image](https://github.com/user-attachments/assets/1fd55d91-9201-44ed-ac75-2355defe67ed)

**Comment by thisisapple** [comment]
I realized the problem was related the parameter named factor.
The problem is fixed when I specify `factor=40`.

`structure.show_displacement(factor=40)`

**Comment by smith120bh** [comment]
@thisisapple : So yes, you can override the scale factor for any plot (that `factor=x` parameter). However, anaStruct also _should be_ automatically figuring out a scale factor that reasonably keeps the deformed structure within the plot window. In your first screenshot, it's clearly not doing that correctly. As long as you were using the most recent anaStruct release, then I'm pretty sure I know where the problem is... I'll try to get to fixing this this weekend.

**Comment by smith120bh** [comment]
@thisisapple : Actually, it turns out that I fixed this already in some recent work I did to add Total Deflection outputs. I've just pushed out a new release (v1.6.1) which now contains those updates and the fix to this bug. So please install v1.6.1 to fix the diagram autoscaling!

Screenshots of your scripts as run on v1.6.1 - which is, I think, what you expect!:
<img width="1200" alt="image" src="https://github.com/user-attachments/assets/f7570c16-5386-4f80-a54b-623fd01873d9">
<img width="1198" alt="image" src="https://github.com/user-attachments/assets/e28845d0-798c-4142-8571-4707ac7e51d5">
