### ISSUE TITLE
bug in hinges

### ISSUE THREAD

**Issue by htca** [ritchie46/anaStruct#44]
Hi,
See the following model:

```
from anastruct.fem.system import SystemElements
ss = SystemElements()
ss.add_element(location=[[0, 0], [5, 0]], EA=5e9, EI=8000, spring={2:0})
ss.add_element(location=[[5, 0], [10, 0]], EA=5e9, EI=8000)

ss.q_load(element_id=1, q=-9)
ss.q_load(element_id=2, q=-9)

ss.add_support_fixed(node_id=1)
ss.add_support_fixed(node_id=3)

ss.solve()
ss.show_structure()
ss.show_reaction_force()
ss.show_shear_force()
ss.show_bending_moment()
ss.show_displacement()
```

It should give at least symmetrical results with support loads of 45 and bending moments of 112.5. Adding a spring with a numerical small value will also lead to different results.

Small request; the use of a kinematic matrix and a constitutive matrix is interesting, is there anyone who has some literature about that?

Marcel

**Comment by smith120bh** [comment]
Okay, I think I'm pinning this down finally. 

**Key fact:** In the above script, if instead of setting the hinge at node 2 of element 1, you set it at node 1 of element 2, then the asymmetry of the results exactly switches. (i.e. higher reaction on the right node rather than left node)

**Digging in:** When a hinge is added to a specific element, then the constitutive matrix _for that element_ is modified to remove stiffness due to that end of the beam (effectively creating a constitutive matrix for a cantilevered beam). It does nothing, however, for the neighbouring element, which still has a constitutive matrix that assumes stiffnesses for a fixed beam. That means that when the global stiffness matrix is assembled, the free rotation of node 2 is incorrectly taken as affecting the moment and shear of the unreleased neighbouring element. 

**The Solution:** I think we need to modify the `ensure_single_hinge()` function to, rather than ensuring at least one element has a moment connection to a node, instead ensuring that every element is hinged and adding a rotation-only support at the affected node (to prevent a singular stiffness matrix). I'll work on that.

This is the correct solution, if I set a hinge on both elements and then manually delete the rotational dof for node 2 from the system_displacement_vector (effectively adding a rotation-only support there):
![image](https://user-images.githubusercontent.com/42363318/105018287-e0530c80-5a98-11eb-9c2a-b770b16a9f6c.png)

And for reference, these are the incorrect results from the above script:
![image](https://user-images.githubusercontent.com/42363318/105018516-3627b480-5a99-11eb-86a9-5558dee2c272.png)
