### ISSUE TITLE
Axial q_load on element in x-direction

### ISSUE THREAD

**Issue by MaximilianFranz** [ritchie46/anaStruct#68]
We were trying to apply a q_load in global x direction to an element that was also in global x direction (`element.angle == 0`). However, because of the check in [`apply_perpendicular_load` ](https://github.com/ritchie46/anaStruct/blob/87d30ac883061c63da8cbaca4c92c2328bd27a75/anastruct/fem/system_components/assembly.py#L58) no q_load was added to the system force matrix. This, we believe, is a bug, because the check for `q_perpendicular == 0` returns True, and then skips the element, albeit the fact that running `apply_parallel_q_load` would result in the correct behaviour for the given load. 

Thus, by swichting the arguments around to: 
```python
        if (
            element.q_direction == "x"
            or element.q_direction == "y"
            or element.dead_load
        ):
            apply_parallel_q_load(system, element)

        elif q_perpendicular == 0:
            continue
```

we were able to fix our issue, but weren't sure why this check was done in this order?

**Comment by smith120bh** [comment]
That solution won't quite work, because a horizontal member with a non-zero dead_load or a q_load with q_direction=="y" would also both get thrown into `apply_parallel_q_load()` incorrectly. However, you're right - there does seem to be some bad logic there; it shouldn't just skip everything if only parallel q_loads loads exist. I'll work on a fix for this!
